POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Front in Sampa",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/937bb4a2-f193-48db-a3b0-9e962980ac63/attendees
Content-Type: application/json

{
  "name": "Gabriel Vitebo",
  "email": "vitebo2@outlook.com"
}